//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.19 at 10:52:54 AM EDT 
//


package com.tesora.dve.tools.jaxb.policy;

/*
 * #%L
 * Tesora Inc.
 * Database Virtualization Engine
 * %%
 * Copyright (C) 2011 - 2014 Tesora Inc.
 * %%
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License, version 3,
 * as published by the Free Software Foundation.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Affero General Public License for more details.
 * 
 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 * #L%
 */

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.tesora.dve.tools.jaxb.policy package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _PolicyConfig_QNAME = new QName("", "policyConfig");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.tesora.dve.tools.jaxb.policy
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link PolicyItem }
     * 
     */
    public PolicyItem createPolicyItem() {
        return new PolicyItem();
    }

    /**
     * Create an instance of {@link PolicyConfig }
     * 
     */
    public PolicyConfig createPolicyConfig() {
        return new PolicyConfig();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PolicyConfig }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "policyConfig")
    public JAXBElement<PolicyConfig> createPolicyConfig(PolicyConfig value) {
        return new JAXBElement<PolicyConfig>(_PolicyConfig_QNAME, PolicyConfig.class, null, value);
    }

}
