// OS_STATUS: public
package com.tesora.dve.sql.transform.strategy;


public enum FeaturePlannerIdentifier {

	DEGENERATE,
	DISTRIBUTION_KEY_EXECUTE,
	GROUP_BY,
	ORDERBY_LIMIT,
	SESSION,
	ORDER_BY,
	JOIN,
	GENERIC_AGG,
	MYSQL_GROUPBY_EXT,
	SINGLE_SITE,
	INSERT_INTO_SELECT,
	REPLACE_INTO,
	UPDATE_DIST_VECT,
	NESTED_QUERY,
	NESTED_QUERY_BROADCAST,
	PROJ_CORSUB,
	WC_CORSUB,
	HAVING,
	UNION,
	DELETE,
	INFO_SCHEMA,
	TIMESTAMP_VARIABLE,
	CONTAINER_BASE_TABLE,
	NULL_LITERAL,
	JOIN_SIMPLIFICATION,
	VIEW,
	TRUNCATE_MT_TABLE;
}
