//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.11.14 at 11:27:14 AM EST 
//


package com.tesora.dve.tools.jaxb.persistent;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.tesora.dve.tools.jaxb.persistent package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _PersistentConfig_QNAME = new QName("", "persistentConfig");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.tesora.dve.tools.jaxb.persistent
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link PersistentGroupCfgList }
     * 
     */
    public PersistentGroupCfgList createPersistentGroupCfgList() {
        return new PersistentGroupCfgList();
    }

    /**
     * Create an instance of {@link PersistentSiteCfgList }
     * 
     */
    public PersistentSiteCfgList createPersistentSiteCfgList() {
        return new PersistentSiteCfgList();
    }

    /**
     * Create an instance of {@link PersistentSiteCfgList.Site }
     * 
     */
    public PersistentSiteCfgList.Site createPersistentSiteCfgListSite() {
        return new PersistentSiteCfgList.Site();
    }

    /**
     * Create an instance of {@link PersistentConfig }
     * 
     */
    public PersistentConfig createPersistentConfig() {
        return new PersistentConfig();
    }

    /**
     * Create an instance of {@link PersistentGroupCfgList.Group }
     * 
     */
    public PersistentGroupCfgList.Group createPersistentGroupCfgListGroup() {
        return new PersistentGroupCfgList.Group();
    }

    /**
     * Create an instance of {@link PersistentSiteCfgList.Site.SiteInstance }
     * 
     */
    public PersistentSiteCfgList.Site.SiteInstance createPersistentSiteCfgListSiteSiteInstance() {
        return new PersistentSiteCfgList.Site.SiteInstance();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PersistentConfig }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "persistentConfig")
    public JAXBElement<PersistentConfig> createPersistentConfig(PersistentConfig value) {
        return new JAXBElement<PersistentConfig>(_PersistentConfig_QNAME, PersistentConfig.class, null, value);
    }

}
