//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.11.14 at 11:27:14 AM EST 
//


package com.tesora.dve.tools.jaxb.persistent;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PersistentConfig complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PersistentConfig">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="persistentSites" type="{}PersistentSiteCfgList"/>
 *         &lt;element name="persistentGroups" type="{}PersistentGroupCfgList" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PersistentConfig", propOrder = {
    "persistentSites",
    "persistentGroups"
})
public class PersistentConfig {

    @XmlElement(required = true)
    protected PersistentSiteCfgList persistentSites;
    protected PersistentGroupCfgList persistentGroups;

    /**
     * Gets the value of the persistentSites property.
     * 
     * @return
     *     possible object is
     *     {@link PersistentSiteCfgList }
     *     
     */
    public PersistentSiteCfgList getPersistentSites() {
        return persistentSites;
    }

    /**
     * Sets the value of the persistentSites property.
     * 
     * @param value
     *     allowed object is
     *     {@link PersistentSiteCfgList }
     *     
     */
    public void setPersistentSites(PersistentSiteCfgList value) {
        this.persistentSites = value;
    }

    /**
     * Gets the value of the persistentGroups property.
     * 
     * @return
     *     possible object is
     *     {@link PersistentGroupCfgList }
     *     
     */
    public PersistentGroupCfgList getPersistentGroups() {
        return persistentGroups;
    }

    /**
     * Sets the value of the persistentGroups property.
     * 
     * @param value
     *     allowed object is
     *     {@link PersistentGroupCfgList }
     *     
     */
    public void setPersistentGroups(PersistentGroupCfgList value) {
        this.persistentGroups = value;
    }

}
