//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.11.01 at 06:28:31 PM EDT 
//


package com.tesora.dve.tools.analyzer.jaxb;

/*
 * #%L
 * Tesora Inc.
 * Database Virtualization Engine
 * %%
 * Copyright (C) 2011 - 2014 Tesora Inc.
 * %%
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License, version 3,
 * as published by the Free Software Foundation.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Affero General Public License for more details.
 * 
 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 * #L%
 */

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for StatementInsertIntoValuesType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="StatementInsertIntoValuesType">
 *   &lt;complexContent>
 *     &lt;extension base="{}StatementPopulationType">
 *       &lt;sequence>
 *         &lt;element name="insertPrefix" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="colWidth" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="population" type="{}InsertTuples" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "StatementInsertIntoValuesType", propOrder = {
    "insertPrefix",
    "colWidth",
    "population"
})
public class StatementInsertIntoValuesType
    extends StatementPopulationType
{

    @XmlElement(required = true)
    protected String insertPrefix;
    protected int colWidth;
    @XmlElement(required = true)
    protected List<InsertTuples> population;

    /**
     * Gets the value of the insertPrefix property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInsertPrefix() {
        return insertPrefix;
    }

    /**
     * Sets the value of the insertPrefix property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInsertPrefix(String value) {
        this.insertPrefix = value;
    }

    /**
     * Gets the value of the colWidth property.
     * 
     */
    public int getColWidth() {
        return colWidth;
    }

    /**
     * Sets the value of the colWidth property.
     * 
     */
    public void setColWidth(int value) {
        this.colWidth = value;
    }

    /**
     * Gets the value of the population property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the population property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPopulation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link InsertTuples }
     * 
     * 
     */
    public List<InsertTuples> getPopulation() {
        if (population == null) {
            population = new ArrayList<InsertTuples>();
        }
        return this.population;
    }

	@Override
	public String getStmt() {
		return insertPrefix;
	}

	@Override
	public void setStmt(String freq) {
		this.setInsertPrefix(freq);
	}
	
	@Override
	public void setFreq(int freq) {
		super.setFreq(freq);
		for (final InsertTuples tuple : this.getPopulation()) {
			tuple.setTuplePop(freq);
		}
	}

}
