//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.11.23 at 04:04:36 PM EST 
//


package com.tesora.dve.sql.template.jaxb;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for FkModeType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="FkModeType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="strict"/>
 *     &lt;enumeration value="ignore"/>
 *     &lt;enumeration value="emulate"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "FkModeType")
@XmlEnum
public enum FkModeType {

    @XmlEnumValue("strict")
    STRICT("strict"),
    @XmlEnumValue("ignore")
    IGNORE("ignore"),
    @XmlEnumValue("emulate")
    EMULATE("emulate");
    private final String value;

    FkModeType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static FkModeType fromValue(String v) {
        for (FkModeType c: FkModeType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
