//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.11.01 at 06:28:31 PM EDT 
//


package com.tesora.dve.tools.analyzer.jaxb;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for IndexType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="IndexType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Statistic"/>
 *     &lt;enumeration value="Clustered"/>
 *     &lt;enumeration value="Hashed"/>
 *     &lt;enumeration value="Other"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "IndexType")
@XmlEnum
public enum IndexType {

    @XmlEnumValue("Statistic")
    STATISTIC("Statistic"),
    @XmlEnumValue("Clustered")
    CLUSTERED("Clustered"),
    @XmlEnumValue("Hashed")
    HASHED("Hashed"),
    @XmlEnumValue("Other")
    OTHER("Other");
    private final String value;

    IndexType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static IndexType fromValue(String v) {
        for (IndexType c: IndexType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
