//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.11.01 at 06:28:31 PM EDT 
//


package com.tesora.dve.tools.analyzer.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for InsertTuples complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="InsertTuples">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="tupleCount" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="tuplePop" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "InsertTuples")
public class InsertTuples {

    @XmlAttribute(name = "tupleCount", required = true)
    protected int tupleCount;
    @XmlAttribute(name = "tuplePop", required = true)
    protected int tuplePop;

    /**
     * Gets the value of the tupleCount property.
     * 
     */
    public int getTupleCount() {
        return tupleCount;
    }

    /**
     * Sets the value of the tupleCount property.
     * 
     */
    public void setTupleCount(int value) {
        this.tupleCount = value;
    }

    /**
     * Gets the value of the tuplePop property.
     * 
     */
    public int getTuplePop() {
        return tuplePop;
    }

    /**
     * Sets the value of the tuplePop property.
     * 
     */
    public void setTuplePop(int value) {
        this.tuplePop = value;
    }

}
