//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.11.01 at 06:28:31 PM EDT 
//


package com.tesora.dve.tools.analyzer.jaxb;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for StatementNonInsertType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="StatementNonInsertType">
 *   &lt;complexContent>
 *     &lt;extension base="{}StatementPopulationType">
 *       &lt;sequence>
 *         &lt;element name="stmt" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "StatementNonInsertType", propOrder = {
    "stmt"
})
public class StatementNonInsertType
    extends StatementPopulationType
{

    @XmlElement(required = true)
    protected String stmt;

    @XmlAttribute(name = "literalCount", required = true)
    protected int literals;

    /**
     * Gets the value of the stmt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStmt() {
        return stmt;
    }

    /**
     * Sets the value of the stmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStmt(String value) {
        this.stmt = value;
    }

    public int getLiteralCount() {
        return literals;
    }

    public void setLiteralCount(int literals) {
        this.literals = literals;
    }
}
