//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.11.01 at 06:28:31 PM EDT 
//


package com.tesora.dve.tools.analyzer.jaxb;

/*
 * #%L
 * Tesora Inc.
 * Database Virtualization Engine
 * %%
 * Copyright (C) 2011 - 2014 Tesora Inc.
 * %%
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License, version 3,
 * as published by the Free Software Foundation.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Affero General Public License for more details.
 * 
 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 * #L%
 */

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TablesType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TablesType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="table" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="columns" type="{}ColumnsType"/>
 *                   &lt;element name="keys" type="{}KeysType"/>
 *                   &lt;element name="indexes" type="{}IndexesType"/>
 *                   &lt;element name="scts" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="rowCount" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                 &lt;attribute name="view" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TablesType", propOrder = {
    "table"
})
public class TablesType {

    protected List<TablesType.Table> table;

    /**
     * Gets the value of the table property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the table property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTable().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TablesType.Table }
     * 
     * 
     */
    public List<TablesType.Table> getTable() {
        if (table == null) {
            table = new ArrayList<TablesType.Table>();
        }
        return this.table;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="columns" type="{}ColumnsType"/>
     *         &lt;element name="keys" type="{}KeysType"/>
     *         &lt;element name="indexes" type="{}IndexesType"/>
     *         &lt;element name="scts" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *       &lt;/sequence>
     *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="rowCount" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
     *       &lt;attribute name="view" type="{http://www.w3.org/2001/XMLSchema}boolean" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "columns",
        "keys",
        "indexes",
        "scts"
    })
    public static class Table {

        @XmlElement(required = true)
        protected ColumnsType columns;
        @XmlElement(required = true)
        protected KeysType keys;
        @XmlElement(required = true)
        protected IndexesType indexes;
        protected String scts;
        @XmlAttribute(name = "name", required = true)
        protected String name;
        @XmlAttribute(name = "rowCount", required = true)
        protected int rowCount;
        @XmlAttribute(name = "view")
        protected Boolean view;

        /**
         * Gets the value of the columns property.
         * 
         * @return
         *     possible object is
         *     {@link ColumnsType }
         *     
         */
        public ColumnsType getColumns() {
            return columns;
        }

        /**
         * Sets the value of the columns property.
         * 
         * @param value
         *     allowed object is
         *     {@link ColumnsType }
         *     
         */
        public void setColumns(ColumnsType value) {
            this.columns = value;
        }

        /**
         * Gets the value of the keys property.
         * 
         * @return
         *     possible object is
         *     {@link KeysType }
         *     
         */
        public KeysType getKeys() {
            return keys;
        }

        /**
         * Sets the value of the keys property.
         * 
         * @param value
         *     allowed object is
         *     {@link KeysType }
         *     
         */
        public void setKeys(KeysType value) {
            this.keys = value;
        }

        /**
         * Gets the value of the indexes property.
         * 
         * @return
         *     possible object is
         *     {@link IndexesType }
         *     
         */
        public IndexesType getIndexes() {
            return indexes;
        }

        /**
         * Sets the value of the indexes property.
         * 
         * @param value
         *     allowed object is
         *     {@link IndexesType }
         *     
         */
        public void setIndexes(IndexesType value) {
            this.indexes = value;
        }

        /**
         * Gets the value of the scts property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getScts() {
            return scts;
        }

        /**
         * Sets the value of the scts property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setScts(String value) {
            this.scts = value;
        }

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName(String value) {
            this.name = value;
        }

        /**
         * Gets the value of the rowCount property.
         * 
         */
        public int getRowCount() {
            return rowCount;
        }

        /**
         * Sets the value of the rowCount property.
         * 
         */
        public void setRowCount(int value) {
            this.rowCount = value;
        }

        /**
         * Gets the value of the view property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public Boolean isView() {
            return view;
        }

        /**
         * Sets the value of the view property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setView(Boolean value) {
            this.view = value;
        }

    }

}
