//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.08.21 at 05:55:21 PM EDT 
//


package com.tesora.dve.sql.raw.jaxb;

/*
 * #%L
 * Tesora Inc.
 * Database Virtualization Engine
 * %%
 * Copyright (C) 2011 - 2014 Tesora Inc.
 * %%
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License, version 3,
 * as published by the Free Software Foundation.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Affero General Public License for more details.
 * 
 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 * #L%
 */

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DMLStepType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DMLStepType">
 *   &lt;complexContent>
 *     &lt;extension base="{}StepType">
 *       &lt;sequence>
 *         &lt;element name="srcsql" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="distkey" type="{}DistKeyValue" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="action" use="required" type="{}DMLType" />
 *       &lt;attribute name="srcmod" use="required" type="{}ModelType" />
 *       &lt;attribute name="srcgrp" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DMLStepType", propOrder = {
    "srcsql",
    "distkey"
})
@XmlSeeAlso({
    ProjectingStepType.class,
    UpdateStepType.class
})
public class DMLStepType
    extends StepType
{

    @XmlElement(required = true)
    protected String srcsql;
    protected DistKeyValue distkey;
    @XmlAttribute(name = "action", required = true)
    protected DMLType action;
    @XmlAttribute(name = "srcmod", required = true)
    protected ModelType srcmod;
    @XmlAttribute(name = "srcgrp", required = true)
    protected String srcgrp;

    /**
     * Gets the value of the srcsql property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSrcsql() {
        return srcsql;
    }

    /**
     * Sets the value of the srcsql property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSrcsql(String value) {
        this.srcsql = value;
    }

    /**
     * Gets the value of the distkey property.
     * 
     * @return
     *     possible object is
     *     {@link DistKeyValue }
     *     
     */
    public DistKeyValue getDistkey() {
        return distkey;
    }

    /**
     * Sets the value of the distkey property.
     * 
     * @param value
     *     allowed object is
     *     {@link DistKeyValue }
     *     
     */
    public void setDistkey(DistKeyValue value) {
        this.distkey = value;
    }

    /**
     * Gets the value of the action property.
     * 
     * @return
     *     possible object is
     *     {@link DMLType }
     *     
     */
    public DMLType getAction() {
        return action;
    }

    /**
     * Sets the value of the action property.
     * 
     * @param value
     *     allowed object is
     *     {@link DMLType }
     *     
     */
    public void setAction(DMLType value) {
        this.action = value;
    }

    /**
     * Gets the value of the srcmod property.
     * 
     * @return
     *     possible object is
     *     {@link ModelType }
     *     
     */
    public ModelType getSrcmod() {
        return srcmod;
    }

    /**
     * Sets the value of the srcmod property.
     * 
     * @param value
     *     allowed object is
     *     {@link ModelType }
     *     
     */
    public void setSrcmod(ModelType value) {
        this.srcmod = value;
    }

    /**
     * Gets the value of the srcgrp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSrcgrp() {
        return srcgrp;
    }

    /**
     * Sets the value of the srcgrp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSrcgrp(String value) {
        this.srcgrp = value;
    }

}
