//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.08.21 at 05:55:21 PM EDT 
//


package com.tesora.dve.sql.raw.jaxb;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ModelType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ModelType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="broadcast"/>
 *     &lt;enumeration value="random"/>
 *     &lt;enumeration value="static"/>
 *     &lt;enumeration value="range"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ModelType")
@XmlEnum
public enum ModelType {

    @XmlEnumValue("broadcast")
    BROADCAST("broadcast"),
    @XmlEnumValue("random")
    RANDOM("random"),
    @XmlEnumValue("static")
    STATIC("static"),
    @XmlEnumValue("range")
    RANGE("range");
    private final String value;

    ModelType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ModelType fromValue(String v) {
        for (ModelType c: ModelType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
