//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.19 at 10:52:54 AM EDT 
//


package com.tesora.dve.tools.jaxb.policy;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PolicyConfig complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PolicyConfig">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="aggregation" type="{}PolicyItem"/>
 *         &lt;element name="small" type="{}PolicyItem"/>
 *         &lt;element name="medium" type="{}PolicyItem"/>
 *         &lt;element name="large" type="{}PolicyItem"/>
 *       &lt;/sequence>
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="strict" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PolicyConfig", propOrder = {
    "aggregation",
    "small",
    "medium",
    "large"
})
public class PolicyConfig {

    @XmlElement(required = true)
    protected PolicyItem aggregation;
    @XmlElement(required = true)
    protected PolicyItem small;
    @XmlElement(required = true)
    protected PolicyItem medium;
    @XmlElement(required = true)
    protected PolicyItem large;
    @XmlAttribute(required = true)
    protected String name;
    @XmlAttribute
    protected Boolean strict;

    /**
     * Gets the value of the aggregation property.
     * 
     * @return
     *     possible object is
     *     {@link PolicyItem }
     *     
     */
    public PolicyItem getAggregation() {
        return aggregation;
    }

    /**
     * Sets the value of the aggregation property.
     * 
     * @param value
     *     allowed object is
     *     {@link PolicyItem }
     *     
     */
    public void setAggregation(PolicyItem value) {
        this.aggregation = value;
    }

    /**
     * Gets the value of the small property.
     * 
     * @return
     *     possible object is
     *     {@link PolicyItem }
     *     
     */
    public PolicyItem getSmall() {
        return small;
    }

    /**
     * Sets the value of the small property.
     * 
     * @param value
     *     allowed object is
     *     {@link PolicyItem }
     *     
     */
    public void setSmall(PolicyItem value) {
        this.small = value;
    }

    /**
     * Gets the value of the medium property.
     * 
     * @return
     *     possible object is
     *     {@link PolicyItem }
     *     
     */
    public PolicyItem getMedium() {
        return medium;
    }

    /**
     * Sets the value of the medium property.
     * 
     * @param value
     *     allowed object is
     *     {@link PolicyItem }
     *     
     */
    public void setMedium(PolicyItem value) {
        this.medium = value;
    }

    /**
     * Gets the value of the large property.
     * 
     * @return
     *     possible object is
     *     {@link PolicyItem }
     *     
     */
    public PolicyItem getLarge() {
        return large;
    }

    /**
     * Sets the value of the large property.
     * 
     * @param value
     *     allowed object is
     *     {@link PolicyItem }
     *     
     */
    public void setLarge(PolicyItem value) {
        this.large = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the strict property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isStrict() {
        return strict;
    }

    /**
     * Sets the value of the strict property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setStrict(Boolean value) {
        this.strict = value;
    }

}
